name: Push to Main

on:
  push:
    branches: ["main"]

jobs:

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Run Tests
        run: go test -v ./...
